name = "dtroyer-com"
main = "src/worker.ts"
compatibility_date = "2025-10-23"

assets = { directory = "public" }

# Uncomment and configure your custom domain after setting it up in Cloudflare
# routes = [
#   { pattern = "dtroyer.com", custom_domain = true }
# ]
